# -*- coding: utf-8 -*-
"""3830app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FhMrVy-O4WYmmJsrimqK9_xvatgKvCtp
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Title
st.title("🚗 Vehicle Popularity Analysis App")
st.markdown("Analyze and visualize vehicle demand trends using clustering models for both used and new car datasets.")

# Load data
@st.cache_data
def load_data():
    used = pd.read_csv("Final_CBB_Listings_NEW(2).csv")
    new = pd.read_csv("Final_CBB_Listings_USED(2).csv")
    brand_used = pd.read_csv("brand_df.csv")
    vehicle_used = pd.read_csv("vehicle_df.csv")
    brand_new = pd.read_csv("brand_new_df_clustered.csv")
    vehicle_new = pd.read_csv("vehicle_new_df_clustered.csv")
    return used, new, brand_used, vehicle_used, brand_new, vehicle_new

used_df, new_df, brand_df, vehicle_df, brand_new_df, vehicle_new_df = load_data()

# Sidebar to choose dataset
option = st.sidebar.selectbox("Select Dataset", ["Used Cars", "New Cars"])

if option == "Used Cars":
    st.header("Used Vehicle Insights")

    st.subheader("🔍 Brand-Level Clusters (Used Cars)")
    fig1, ax1 = plt.subplots(figsize=(10, 5))
    sns.scatterplot(data=brand_df, x="PCA1", y="PCA2", hue="brand_cluster", s=100, palette="Set2", ax=ax1)
    for i in range(brand_df.shape[0]):
        ax1.text(brand_df['PCA1'][i], brand_df['PCA2'][i], brand_df['make'][i], fontsize=8)
    st.pyplot(fig1)

    st.subheader("📊 Vehicle-Level Clusters (Used Cars)")
    fig2, ax2 = plt.subplots(figsize=(10, 5))
    sns.scatterplot(data=vehicle_df, x="PCA1", y="PCA2", hue="vehicle_cluster", s=30, palette="cool", ax=ax2)
    st.pyplot(fig2)

else:
    st.header("New Vehicle Insights")

    st.subheader("🔍 Brand-Level Clusters (New Cars)")
    fig3, ax3 = plt.subplots(figsize=(10, 5))
    sns.scatterplot(data=brand_new_df, x="PCA1", y="PCA2", hue="brand_cluster", s=100, palette="Set2", ax=ax3)
    for i in range(brand_new_df.shape[0]):
        ax3.text(brand_new_df['PCA1'][i], brand_new_df['PCA2'][i], brand_new_df['make'][i], fontsize=8)
    st.pyplot(fig3)

    st.subheader("📊 Vehicle-Level Clusters (New Cars)")
    fig4, ax4 = plt.subplots(figsize=(10, 5))
    sns.scatterplot(data=vehicle_new_df, x="PCA1", y="PCA2", hue="vehicle_cluster", s=30, palette="cool", ax=ax4)
    st.pyplot(fig4)

st.sidebar.markdown("---")
st.sidebar.write("Developed by Gurleen Kaur 💡")